# Generated by Django 6.0.2 on 2026-02-05 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('total_count', models.IntegerField(default=0)),
                ('avg_flowrate', models.FloatField(default=0)),
                ('avg_pressure', models.FloatField(default=0)),
                ('avg_temperature', models.FloatField(default=0)),
                ('type_distribution', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('flowrate', models.FloatField()),
                ('pressure', models.FloatField()),
                ('temperature', models.FloatField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='equipment.datasetupload')),
            ],
        ),
    ]
